// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "adder": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=goa_sample/design
// --out=$(GOPATH)/src/goa_sample
// --version=v1.3.0

package app
